lecture/ssafy_190312/first_local/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.article_list, name='article_list'),  # list.html
    # path('new/', views.new_article, name='new_article'),  # new.html
    path('create/', views.create_article, name='create_article'),  # create

    path('<int:article_id>/', views.article_detail, name='article_detail'),  # detail.html
    # path('<int:article_id>/edit/', views.edit_article, name='edit_article'),  # edit.html
    path('<int:article_id>/update/', views.update_article, name='update_article'),  # update
    path('<int:article_id>/delete/', views.delete_article, name='delete_article'),  # delete

    path('<int:article_id>/create_comment/', views.create_comment, name='create_comment'),  # create comment
    path('<int:article_id>/delete_comment/<int:comment_id>/',
         views.delete_comment, name='delete_comment'),  # delete comment
]

lecture/ssafy_190312/first_local/first_local/urls.py
from django.contrib import admin
from django.urls import path, include

# upload setting
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('sns/', include('sns.urls')),
]

# Dev only (개발 서버에서 media/ 파일들 서빙 미지원)
# settings.py 에서 DEBUG = False 되면, 자동으로 static(...)은 [] (빈 리스트)를 리턴
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lecture/ssafy_190312/first_local/sns/urls.py
from django.urls import path
from . import views


app_name = 'sns'

urlpatterns = [
    path('', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('create/', views.create_posting, name='create_posting'),

    path('<int:posting_id>/comment/create/', views.create_comment, name='create_comment'),
]

lecture/ssafy_190312/first_local/board/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.TextField(default='')
    content = models.TextField(default='')
    like = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.id}: {self.title[:20]}'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.article.title}: {self.content}'

lecture/ssafy_190312/first_local/sns/models.py
from django.db import models

# ImageKit
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFit


class Posting(models.Model):
    content = models.TextField(default='')
    icon = models.CharField(max_length=20, default='fas fa-question')

    # # upload URL => /media/posting/origin/20190312/
    # image = models.ImageField(blank=True, upload_to='posting/origin/%Y%m%d')

    # resize
    image = ProcessedImageField(
        upload_to='posting/resize/%Y%m%d',
        processors=[ResizeToFit(width=960, upscale=False)],  # upscale 의 의미: 작은거를 늘릴건지
        format='JPEG'
    )

    # thumbnail
    image_thumbnail = ImageSpecField(
        source='image',  # 위에서 만든 resize 된 이미지 변수명
        processors=[ResizeToFit(width=320, upscale=False)],
        format='JPEG',
        options={'quality': 60}
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.content[:20]}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        print()
        print(f'=== Saved Posting with id: {self.id} ===')
        print(f'    content: {self.content}')
        if self.image:
            print(f'    imaze_size: {self.image.width}px * {self.image.height}px: {round(self.image.size / 1024)}kb')
        print('=========================================')
        print()


class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.posting.content[:10]}: {self.content[:20]}'

lecture/ssafy_190312/first_local/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
# from IPython import embed

# Create your views here.


def article_list(request):
    articles = Article.objects.all()
    return render(request, 'board/list.html', {
        'articles': articles,
    })


def article_detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    comments = article.comment_set.all()
    return render(request, 'board/detail.html', {
        'article': article,
        'comments': comments,
    })


# def new_article(request):
#     return render(request, 'board/new.html')


def create_article(request):
    if request.method == 'GET':
        return render(request, 'board/new.html')
    else:  # request.method == 'POST'
        article = Article()
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect('board:article_detail', article.id)


# def edit_article(request, article_id):
#     pass


def update_article(request, article_id):
    if request.method == 'GET':
        article = get_object_or_404(Article, id=article_id)
        return render(request, 'board/edit.html', {
            'article': article,
        })

    else:  # request.method == 'POST'
        article = get_object_or_404(Article, id=article_id)
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect('board:article_detail', article.id)


def delete_article(request, article_id):
    if request.method == 'POST':
        article = get_object_or_404(Article, id=article_id)
        article.delete()
    return redirect('board:article_list')


def create_comment(request, article_id):
    if request.method == 'POST':
        comment = Comment()
        comment.article = get_object_or_404(Article, id=article_id)
        comment.content = request.POST.get('comment')

        comment.save()
    return redirect('board:article_detail', article_id)


def delete_comment(request, article_id, comment_id):
    if request.method == 'POST':
        comment = get_object_or_404(Comment, id=comment_id)
        comment.delete()

    return redirect('board:article_detail', article_id)

lecture/ssafy_190312/first_local/sns/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Posting, Comment

# Create your views here.


def posting_list(request):
    postings = Posting.objects.all().order_by('updated_at')

    return render(request, 'sns/list.html', {
        'postings': postings,
    })


def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comments = posting.comment_set.all().order_by('-created_at')

    return render(request, 'sns/detail.html', {
        'posting': posting,
        'comments': comments,
    })


def create_posting(request):
    if request.method == "POST":
        posting = Posting.objects.create(
            content=request.POST.get('content'),
            icon=request.POST.get('icon'),
            image=request.FILES.get('image')
        )

        return redirect('sns:posting_detail', posting.id)
    else:
        return redirect('sns:posting_list')


def create_comment(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)

    if request.method == "POST":
        comment = Comment()
        comment.content = request.POST.get('comment')
        comment.posting = posting
        comment.save()

    return redirect('sns:posting_detail', posting_id)

lecture/ssafy_190312/first_local/sns/templates/sns/_forms.html
<header class="mt-3">
    <form action="{% url 'sns:create_posting' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row align-items center">
            <!-- icon select tag -->
            <div class="col-auto my-1">
                <label for="icon" class="sr-only">icon</label>
                <select name="icon" id="icon" class="custom-select mr-sm-2">
                    <option value="fas fa-question">?</option>
                    <option value="far fa-smile">:)</option>
                    <option value="far fa-angry">:(</option>
                    <option value="far fa-smile-wink">;)</option>
                    <option value="fab fa-angrycreative">AngryCreative</option>
                </select>
            </div>

            <!-- content input tag -->
            <div class="col-sm-6 my-1">
                <label for="content" class="sr-only">content</label>
                <input type="text" name="content" id="content" class="form-control" placeholder="Feels like...">
            </div>

            <!-- image/file input tag -->
            <div class="col-sm-4 my-1 input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        Upload
                    </span>
                </div>
                <div class="custom-file">
                    <label for="image" class="custom-file-label">Choose image</label>
                    <input type="file" id="image" name="image" class="custom-file-input" accept="image/*">
                </div>
            </div>

            <!-- submit button -->
            <div class="col-auto my-1">
                <button type="submit" class="btn btn-primary">submit</button>
            </div>

        </div>
    </form>
</header>

lecture/ssafy_190312/first_local/sns/templates/sns/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>My SNS</title>
</head>
<body>
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link {% block is_list %}{% endblock %}" href="{% url 'sns:posting_list' %}">SNS</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% block is_detail %}{% endblock %}" aria-disabled="true">Posting</a>
    </li>
</ul>

    <div class="container">
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

lecture/ssafy_190312/first_local/sns/templates/sns/detail.html
{% extends 'sns/base.html' %}

{% block is_detail %}
    active
{% endblock %}

{% block body %}
    <div class="row mt-3">
        <div class="col-12 col-md-6">
            <div class="card">
                {% if posting.image %}
                    <img src="{{ posting.image.url }}"
                         class="card-img-top image-fluid"
                         alt="{{ posting.image }}">
                {% else %}
                    <img src="http://picsum.photos/g/320/500/?random"
                         class="card-img-top image-fluid"
                         alt="random_image">
                {% endif %}

                <div class="card-body">
                    <i class="{{ posting.icon }} fa-3x"></i>
                    <hr>
                    <p class="card-text">
                        {{ posting.content }}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="card mb-2">
                <div class="card-body">
                    <form action="{% url 'sns:create_comment' posting.id %}" method="POST">
                        {% csrf_token %}
                        <label for="comment">Leave comment</label>
                        <input type="text" name="comment" id="comment" class="form-control" autofocus>
                    </form>
                </div>
            </div>
            <div class="card">
                <ul class="list-group list-group-flush">
                    {% if comments %}
                        {% for comment in comments %}
                            <li class="list-group-item mb-1">
                                {{ comment.content }}
                            </li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item mb-1">No comment yet...</li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

lecture/ssafy_190312/first_local/sns/templates/sns/list.html
{% extends 'sns/base.html' %}

{% block is_list %}
    active
{% endblock %}

{% block body %}
    {% include 'sns/_forms.html' %}
    <hr>
    {% if postings %}
        <section class="card-columns">
            {% for posting in postings %}
                <article class="card mb-2">
                    <a href="{% url 'sns:posting_detail' posting.id %}">
                        {% if posting.image %}
                            <img src="{{ posting.image_thumbnail.url }}"
                                 class="card-img-top image-fluid"
                                 alt="{{ posting.image }}">
                        {% else %}
                            <img src="http://picsum.photos/g/32{{ forloop.counter }}/500/?random"
                             class="card-img-top image-fluid"
                             alt="random_image_{{ forloop.counter }}">
                        {% endif %}

                    </a>
                    <div class="card-body">
                        <i class="{{ posting.icon }} fa-2x"></i>
                    </div>
                </article>
            {% endfor %}
        </section>
    {% endif %}
{% endblock %}