ssafy_project/last_project/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.list, name="list"),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_id>/', views.detail, name='detail'),
    path('<int:user_id>/follow/', views.follow, name="follow"),
    path('<int:user_id>/followers/', views.followers, name="followers"),
    path('<int:user_id>/followings/', views.followings, name="followings"),
]

ssafy_project/last_project/last_project/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views as movie_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('', movie_views.movie_list),
]

ssafy_project/last_project/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_id>/', views.detail, name="detail"),
    path('<int:movie_id>/score/new', views.create_score, name='create_score'),
    path('<int:movie_id>/score/<int:score_id>/delete', views.delete_score, name="delete"),
    path('<int:movie_id>/score/<int:score_id>/update', views.update_score, name="update"),
    path('dbmake/', views.movie_db),
    path('dbmake2/', views.movie_db2),
]

ssafy_project/last_project/movies/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Genre(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name


class Movie(models.Model):
    movie_code = models.TextField()
    movie_name_ko = models.TextField()
    movie_name_en = models.TextField()
    showTm = models.TextField()
    openDt = models.TextField()
    watch_grade_nm = models.TextField()
    audience = models.IntegerField()
    actors = models.TextField()
    directors = models.TextField()
    description = models.TextField()
    poster_url = models.TextField()
    # genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    genre = models.TextField()

    def __str__(self):
        return self.movie_name_ko


class Score(models.Model):
    content = models.TextField()
    value = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

ssafy_project/last_project/movies/forms.py
from django import forms
from .models import Score

class ScoreForm(forms.ModelForm):
    content = forms.CharField(label = "content", widget=forms.Textarea(attrs={
                'rows' : 1,
                'cols' : 20,
            }))
    class Meta:
        model = Score
        fields = ['content', 'value']
        widget = {
            'content' : forms.Textarea
        }

ssafy_project/last_project/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Score
from .forms import ScoreForm
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required

from bs4 import BeautifulSoup as bs
import datetime
import requests


# Create your views here.
def movie_db(request):
    API_KEY = 'e4782a1ecd7ea361da31b4c4f2f5a02b'
    today = ''.join(str(datetime.date.today() - datetime.timedelta(days=1)).split('-'))  # 오늘 날짜

    url_boxoffice = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key={}&targetDt={}&weekGb=0'.format(API_KEY, today)

    res = requests.get(url_boxoffice)
    res_data = res.json().get('boxOfficeResult').get('dailyBoxOfficeList')
    boxoffice = []
    audience = []
    for i in range(len(res_data)):
        boxoffice.append(res_data[i]['movieCd'])
        audience.append(res_data[i]['audiAcc'])

    movies = []
    for movie_code in boxoffice:
        url_movie = "http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key={}&movieCd={}".format(API_KEY, movie_code)
        res = requests.get(url_movie)
        res_data = res.json().get('movieInfoResult').get('movieInfo')

        movies.append({
            'movie_code': res_data.get('movieCd'),
            'movie_name_ko': res_data.get('movieNm'),
            'movie_name_en': res_data.get('movieNmEn'),
            'showTm': res_data.get('showTm'),
            'openDt': '.'.join([res_data.get('openDt')[:4],res_data.get('openDt')[4:6],res_data.get('openDt')[6:]]),
            'genre': ', '.join([x['genreNm'] for x in res_data.get('genres')]),
            'watch_grade_nm': res_data.get('audits')[0].get('watchGradeNm'),
        })

    headers_naver = {
        'X-Naver-Client-Id': 'bS2KxFME66tpq5UJPclw',
        'X-Naver-Client-Secret': 'ZUOJVkLobP'
    }

    for i in range(len(movies)):
        url_naver = "https://openapi.naver.com/v1/search/movie.json?query={}".format(movies[i].get('movie_name_ko'))

        res = requests.get(url_naver, headers=headers_naver)
        res_data = res.json().get('items')

        if res_data:
            res_data = res_data[0]
            movies[i]['audience'] = audience[i]
            # movies[i]['score'] = res_data.get('userRating')
            movies[i]['actors'] = res_data.get('actor')[:-1]
            movies[i]['directors'] = res_data.get('director')[:-1]
            url_content = res_data.get('link')

            response = requests.get(url_content).text
            document = bs(response, 'html.parser')
            temp_content = document.select('.story_area .con_tx')
            content = str(temp_content)[19:-5].replace('\r', '').split('<br/>\xa0')
            movies[i]['description'] = '\n'.join(content)

            temp_img = document.select('.wide_info_area .poster')
            movies[i]['poster_url'] = str(temp_img).split('src=')[2].split('?type=')[0].replace('"', '')

    for movie_data in movies:
        movie = Movie()
        movie.movie_code = movie_data['movie_code']
        movie.movie_name_ko = movie_data['movie_name_ko']
        movie.movie_name_en = movie_data['movie_name_en']
        movie.showTm = movie_data['showTm']
        movie.openDt = movie_data['openDt']
        movie.watch_grade_nm = movie_data['watch_grade_nm']
        movie.audience = movie_data['audience']
        movie.actors = movie_data['actors']
        movie.directors = movie_data['directors']
        movie.description = movie_data['description']
        movie.poster_url = movie_data['poster_url']
        movie.genre = movie_data['genre']
        movie.save()

    return redirect('movies:movie_list')


def movie_db2(request):
    movie = {}

    url_rank = 'https://movie.naver.com/movie/sdb/rank/rmovie.nhn'

    response = requests.get(url_rank).text
    document = bs(response, 'html.parser')
    temp_rank = document.select('.list_ranking .title a')

    temp_li = str(temp_rank).split('href="')[1:]
    for i in range(len(temp_li)):
        temp_li[i] = temp_li[i].split('" title')[0]

    for i in range(1):
        url_movie = 'https://movie.naver.com' + temp_li[i]
        response = requests.get(url_movie).text
        document = bs(response, 'html.parser')

        temp_content = document.select('.story_area .con_tx')
        content = str(temp_content)[19:-5].replace('\r', '').split('<br/>\xa0')
        movie['description'] = '\n'.join(content)

        temp_img = document.select('.wide_info_area .poster')
        movie['poster_url'] = str(temp_img).split('src=')[2].split('?type=')[0].replace('"', '')

        temp_title = document.select('.wide_info_area .mv_info .h_movie a')
        movie['movie_name_ko'] = str(temp_title).split('</a>')[0].split('">')[1]

    return render(request, 'movies/index.html')


def movie_list(request):
    movies = Movie.objects.all()[:10]
    return render(request, 'movies/list.html', {'movies': movies})


def detail(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    if request.GET.get("theaterCode"):
        theatercode = request.GET.get("theaterCode")
    else:
        theatercode = '0056'

    url_movie = 'http://www.cgv.co.kr/theaters/'+f'?theaterCode={theatercode}'
    response = requests.get(url_movie).text
    document = bs(response, 'html.parser')

    temp_address = document.select('.wrap-theater .sect-theater .box-contents .title')
    address = str(temp_address).split('<br/>')[1].split('<a')[0]

    headers_naver_map = {
        'X-NCP-APIGW-API-KEY-ID': 'x8w0y9djtb',
        'X-NCP-APIGW-API-KEY': 'yD4XS0AedH9ShyGuFxMuI5UxqaKNzfrHapjviGkg'
    }

    url_geocode = f'https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query={address}'

    res = requests.get(url_geocode, headers=headers_naver_map)
    res_data = res.json()

    if not res_data.get('addresses'):
        url_movie = 'http://www.cgv.co.kr/theaters/' + f'?theaterCode={theatercode}'
        response = requests.get(url_movie).text
        document = bs(response, 'html.parser')

        temp_address = document.select('.wrap-theater .sect-theater .box-contents .title')
        address = '서울' + str(temp_address).split('서울')[1].split('<br/>')[0]

        url_geocode = f'https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query={address}'

        res = requests.get(url_geocode, headers=headers_naver_map)
        res_data = res.json()

    theaters = {
        '0056': 'CGV강남', '0001': 'CGV강변', '0229': 'CGV건대입구', '0010': 'CGV구로', '0063': 'CGV대학로',
        '0252': 'CGV동대문', '0230': 'CGV등촌', '0009': 'CGV명동', '0105': 'CGV명동역 씨네라이브러리', '0011': 'CGV목동',
        '0057': 'CGV미아', '0030': 'CGV불광', '0046': 'CGV상봉', '0083': 'CGV성신여대입구', '0088': 'CGV송파',
        '0276': 'CGV수유', '0150': 'CGV신촌아트레온', '0040': 'CGV압구정', '0112': 'CGV여의도', '0059': 'CGV영등포',
        '0074': 'CGV왕십리', '0013': 'CGV용산아이파크몰', '0131': 'CGV중계', '0199': 'CGV천호', '0107': 'CGV청담씨네시티',
        '0223': 'CGV피카디리1958', '0164': 'CGV하계', '0191': 'CGV홍대', '0040': 'CINE de CHEF 압구정', '0013': 'CINE de CHEF 용산아이파크몰',
        '0012': 'CGV수원', '0253': 'CGV해운대',
    }

    headers_naver = {
        'X-Naver-Client-Id': 'bS2KxFME66tpq5UJPclw',
        'X-Naver-Client-Secret': 'ZUOJVkLobP'
    }

    url_search = f'https://openapi.naver.com/v1/search/local.json?query={address} 맛집'
    res = requests.get(url_search, headers=headers_naver)
    restaurants = res.json().get('items')

    for r in restaurants:
        address = r.get('address')
        url_geocode = f'https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query={address}'

        res = requests.get(url_geocode, headers=headers_naver_map)
        res_data1 = res.json()
        r['x_axis'] = res_data1.get('addresses')[0].get('x')
        r['y_axis'] = res_data1.get('addresses')[0].get('y')

    sum_score = 0
    avg_score = 0
    list_score = movie.score_set.all()
    if list_score:
        for m_score in list_score:
            sum_score += m_score.value
        avg_score = round(sum_score / len(list_score), 2)

    context = {
        'movie': movie,
        'x_axis': res_data.get('addresses')[0].get('x'),
        'y_axis': res_data.get('addresses')[0].get('y'),
        'theater_code': theaters,
        'theater': theaters.get(str(theatercode)),
        'restaurants': restaurants,
        'avg_score': avg_score,
    }

    return render(request, 'movies/detail.html', context)


@login_required
def create_score(request, movie_id):
    if request.method == 'POST':
        score = ScoreForm(request.POST)
        if score.is_valid():
            form = score.save(commit=False)
            form.movie_id = movie_id
            form.user = request.user
            form.save()
            return redirect('movies:detail', movie_id=movie_id)
        return redirect('movies:detail', movie_id=movie_id)
    return redirect('movies:detail')


@login_required
def create_score(request, movie_id):
    if request.method == 'POST':
        score = ScoreForm(request.POST)
        if score.is_valid():
            form = score.save(commit=False)
            form.movie_id = movie_id
            form.user = request.user
            form.save()
            return redirect('movies:detail', movie_id=movie_id)
        return redirect('movies:detail', movie_id=movie_id)
    return redirect('movies:detail')


@login_required
def delete_score(request, movie_id, score_id):
    if request.method == 'POST':
        score = get_object_or_404(Score, id=score_id)
        score.delete()
        return redirect('movies:detail', movie_id=movie_id)
    return redirect('movies:movie_list')


@login_required
def update_score(request, score_id, movie_id):
    score = get_object_or_404(Score, id=score_id)
    movie = get_object_or_404(Movie, id=movie_id)
    if score.user != request.user:
        return HttpResponseForbidden("You are not allowed to update this Article")

    if request.method == 'POST':
        form = ScoreForm(request.POST, instance=score)

ssafy_project/last_project/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>영화 정보 조회</title>
{% endblock %}

{% block body %}
<div class="jumbotron">
    <div class="container">
        <div class="card mb-3" style="max-width: 1200px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{movie.poster_url}}" class="card-img" alt="Movie Poster" width="320" height="550">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h1 class="card-title mb-0">{{movie.movie_name_ko}} </h1>
                        <p class="card-text" ><small class="text-muted">{{movie.movie_name_en}}</small></p>
                        <p class="card-text"> 관람연령 : {{movie.watch_grade_nm}}</p>
                        <p class="card-text"> 장르 : {{movie.genre}} | {{movie.showTm}}분 </p>
                        <p class="card-text"> 개봉일 : {{movie.openDt}} 개봉</p>
                        <p class="card-text"> 누적관객 : {{movie.audience}}명</p>

                        {% if avg_score %}
                            <p class="card-text"> 평균 평점 : {{ avg_score }}</p>
                        {% endif %}
                        <hr>
                        <p class="card-text"><small class="text-muted">{{movie.description}}</small></p>
                        <a class="btn btn-dark" href="{% url 'movies:movie_list' %}" role="button">목록으로</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block container %}

<div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">서울</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for key, value in theater_code.items %}
                    <td><a href="./?theaterCode={{ key }}" class="btn btn-sm" role="button" aria-pressed="true">{{ value }}</a></td>
                    {% if forloop.counter == 6 or forloop.counter == 12 or forloop.counter == 18 or forloop.counter == 24 or forloop.counter == 30 %}
                        </tr>
                        <tr>
                    {% endif %}
                {% endfor %}
            </tr>
        </tbody>
    </table>
</div>

<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=x8w0y9djtb&callback=initMap"></script>
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=x8w0y9djtb&submodules=geocoder"></script>
<div class="mb-5" id="map" style="width:100%;height:400px;"></div>

<script type="text/javascript">
    var map = new naver.maps.Map('map', {
        zoomControl: true,
        zoomControlOptions: {
            style: naver.maps.ZoomControlStyle.LARGE,
            position: naver.maps.Position.TOP_RIGHT
        },
        mapTypeControl: true,
        center: new naver.maps.LatLng({{ y_axis }},{{ x_axis }}),
        zoom: 11
    });

    var restaurants = {{ restaurants | safe }}

    var markers = []
    var links = []

    for (var i = 0; i < restaurants.length; i++) {
        var rt = restaurants[i]

        if (rt['category'].includes('중식')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/chinese.png' %}',
                    size: new naver.maps.Size(50, 33)
                }
            }));
        }
        else if (rt['category'].includes('인도')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/indian.png' %}',
                    size: new naver.maps.Size(50, 41)
                }
            }));
        }
        else if (rt['category'].includes('햄버거')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/burger.png' %}',
                    size: new naver.maps.Size(40, 37)
                }
            }));
        }
        else if (rt['category'].includes('양식') || rt['category'].includes('스테이크') || rt['category'].includes('스페인')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/western.png' %}',
                    size: new naver.maps.Size(50, 39)
                }
            }));
        }
        else if (rt['category'].includes('일식') || rt['category'].includes('회') || rt['category'].includes('초밥')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/japanese.png' %}',
                    size: new naver.maps.Size(50, 39)
                }
            }));
        }
        else if (rt['category'].includes('국수')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/noodle.png' %}',
                    size: new naver.maps.Size(50, 36)
                }
            }));
        }
        else if (rt['category'].includes('카페')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/cafe.png' %}',
                    size: new naver.maps.Size(50, 38)
                }
            }));
        }
        else if (rt['category'].includes('치킨')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/chicken.png' %}',
                    size: new naver.maps.Size(50, 33)
                }
            }));
        }
        else if (rt['category'].includes('이탈리아') || rt['category'].includes('파스타')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/italian.png' %}',
                    size: new naver.maps.Size(50, 42)
                }
            }));
        }
        else if (rt['category'].includes('술') || rt['category'].includes('바')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/bar.png' %}',
                    size: new naver.maps.Size(50, 54)
                }
            }));
        }
        else if (rt['category'].includes('고기')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/pork.png' %}',
                    size: new naver.maps.Size(50, 38)
                }
            }));
        }
        else if (rt['category'].includes('한식') || rt['category'].includes('뷔페')) {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
                icon: {
                    url: '{% static 'img/korean.png' %}',
                    size: new naver.maps.Size(40, 42)
                }
            }));
        }
        else {
            markers.push(new naver.maps.Marker({
                title: rt['title'] + "\n" + rt['category'],
                position: new naver.maps.LatLng(rt['y_axis'], rt['x_axis']),
                map: map,
            }));
        }

        links.push(rt['link'])
        naver.maps.Event.addListener(markers[i], 'click', getClickHandler(i));
    }

    function getClickHandler(seq) {
        return function(e) {
            var link = links[seq]
            if (link){
                window.open(link)
            }
        }
    }

    var marker = new naver.maps.Marker({
        title: '{{ theater }}',
        position: new naver.maps.LatLng({{ y_axis }},{{ x_axis }}),
        map: map,
        icon: {
            url: '{% static 'img/cgv_logo.png' %}',
            size: new naver.maps.Size(50, 20)
        }
    });

    console.log(marker)

</script>

<h2>영화 평가 목록</h2>

{% if user.is_authenticated %}

<form method="POST" action= "{% url 'movies:create_score' movie.id %}">
    {% csrf_token %}
    <div>
        <ul>
            <li> 평가 <input type="text" class="form-control" name="content" placeholder="평가를 입력해주세요."></li>
            <li> 평점 <input type="number" class="form-control" name="value" placeholder="평점을 선택해주세요."></li>
        </ul>
        <button type = "submit" class="btn btn-dark" >등록하기</button>
    </div>
</form>
<hr>

{% else %}
<form method="POST" action= "{% url 'accounts:login' %}">
    {% csrf_token %}
    <div>
        <ul>
            <li> 평가 <input type="text" class="form-control" name="content" placeholder="로그인 후 이용가능한 서비스입니다."></li>
            <li> 평점 <input type="number" class="form-control" name="value" placeholder="로그인 후 이용가능한 서비스입니다."></li>
        </ul>
        <button type = "submit" class="btn btn-light" >로그인</button>
    </div>
</form>
<hr>

{% endif %}

<div class="list-group">
    {% for score in movie.score_set.all %}
        <a href="{% url 'accounts:detail' score.user.id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">평가 : {{ score.content}}</h5>
                <small>{{ score.created_at }}</small>
            </div>
            <h5 class="mb-1">  ★★★★★ : {{score.value}}</h5>
            <small>  작성자 : {{ score.user.username }}</small>

            <div>
                {% if user == score.user %}
                <hr>
                <form method="POST" action="{% url 'movies:delete' movie.id score.id %}" style="display:inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-dark">삭제</button>
                </form>

                <form method="GET" action="{% url 'movies:update' movie.id score.id %}" style="display:inline">
                    <button type="submit" class="btn btn-dark">수정</button>
                </form>
                {% endif %}
            </div>
        </a>
    {% endfor %}
</div>

{% endblock %}

ssafy_project/last_project/movies/templates/movies/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>MoM</title>
{% endblock %}
    
{% block container %}
    <div class="row my-5">
        {% for movie in movies %}
            <div class="col-sm-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="{% url 'movies:detail' movie_id=movie.id %}">
                            <div class="overlay">
                                <span class="tit">{{movie.movie_name_ko}}</span>
                                <span class="director">감독: {{movie.directors}}</span>
                                <span class="actor">배우: {{movie.actors}}</span>
                                <span class="btn_detail">자세히 보기</span>
                            </div>
                            <img src="{{movie.poster_url}}" alt="Movie Poster" width="224" height="320">
                        </a>
                    </div>
                </div>
            </div>
            {% if forloop.counter == 4 or forloop.counter == 8 %}
        </div>
        <div class="row my-5">
            {% endif %}
        {% endfor %}
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <img src="{% static 'img/nike.png' %}" alt="광고" width="510" height="320">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ssafy_project/last_project/movies/templates/movies/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Update</title>
{% endblock %}

{% block body %}
<div class="jumbotron">
    <div class="container">
        <div class="card mb-3" style="max-width: 1200px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{movie.poster_url}}" class="card-img" alt="Movie Poster" width="320" height="550">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h1 class="card-title mb-0">{{movie.movie_name_ko}} </h1>
                        <p class="card-text" ><small class="text-muted">{{movie.movie_name_en}}</small></p>
                        <p class="card-text"> 관람연령 : {{movie.watch_grade_nm}}</p>
                        <p class="card-text"> 장르 : {{movie.genre}} | {{movie.showTm}}분 </p>
                        <p class="card-text"> 개봉일 : {{movie.openDt}} 개봉</p>
                        <p class="card-text"> 누적관객 : {{movie.audience}}명</p>

                        {% if avg_score %}
                            <p class="card-text"> 평균 평점 : {{ avg_score }}</p>
                        {% endif %}
                        <hr>
                        <p class="card-text"><small class="text-muted">{{movie.description}}</small></p>
                        <a class="btn btn-dark" href="{% url 'movies:movie_list' %}" role="button">목록으로</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block container %}
<h1>평점 수정하기</h1>

<div class="card mb-3">
    <div class="card-body">
        <form method = "POST">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" value="수정하기" class="btn btn-dark"/>
        </form>
    </div>
</div>
{% endblock %}