lecture/ssafy_190322/todo/shout/urls.py
from django.urls import path
from . import views

app_name = 'shout'

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('<int:shout_id>/update/', views.update, name='update'),
]

lecture/ssafy_190322/todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('todos.urls')),
    path('shout/', include('shout.urls')),
]

lecture/ssafy_190322/todo/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index),
    path('home/', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('check/<int:todo_id>/', views.check, name='check'),
    path('delete/<int:todo_id>/', views.delete, name='delete'),
]

lecture/ssafy_190322/todo/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register, name='register'),
]

lecture/ssafy_190322/todo/shout/models.py
from django.db import models

# Create your models here.


class Shout(models.Model):
    title = models.CharField(max_length=30)
    content = models.CharField(max_length=100)


    def __str__(self):
        return f"{self.title}"

lecture/ssafy_190322/todo/todos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Todo(models.Model):
    content = models.TextField()
    completed = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.content}"

lecture/ssafy_190322/todo/shout/forms.py
from django import forms
from .models import Shout


class ShoutForm(forms.Form):
    title = forms.CharField(max_length=30)
    content = forms.CharField(max_length=100)


class ShoutModelForm(forms.ModelForm):
    class Meta:
        model = Shout
        fields = '__all__'
        widgets = {
            'content': forms.TextInput(attrs={
                'class': 'form-control'
            })
        }

lecture/ssafy_190322/todo/todos/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = '__all__'


# class ScoreForm(forms.ModelForm):
#     class Meta:
#         model = Score
#         fields = '__all__'

lecture/ssafy_190322/todo/shout/views.py
from django.shortcuts import render, redirect
from .models import Shout
from .forms import ShoutModelForm


# Create your views here.


def home(request):
    # form을 보여주기 & 문의사항 전부 보여주기
    shouts = Shout.objects.all()
    context = {
        'shouts': shouts,
    }
    return render(request, 'shout/home.html', context)


def create(request):
    if request.method == "POST":
        # 고객센터 문의 작성하기
        form = ShoutModelForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('shout:home')
    else:
        form = ShoutModelForm()
        context = {
            'form': form,
        }
        return render(request, 'shout/form.html', context)


def update(request, shout_id):
    if request.method == "POST":
        # 수정하기(update)
        form = ShoutModelForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('shout:home')
    else:
        # 편집하기(edit)
        shout = Shout.objects.get(id=shout_id)
        form = ShoutModelForm(instance=shout)
        context = {
            'form': form,
        }
        return render(request, 'shout/form.html', context)

lecture/ssafy_190322/todo/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo
from django.contrib.auth.models import User
from .forms import TodoForm

# Create your views here.


def index(request):
    return redirect('todos:home')


def home(request):
    if request.user.is_authenticated:
        # todos = T`odo.objects.filter(user_id=request.user).order_by('completed', '-id')
        todos = request.user.todo_set.order_by('completed', '-id')
        return render(request, 'todos/home.html', {
            'todos': todos
        })
    else:
        todos = None
        return render(request, 'todos/home.html', {
            'todos': todos
        })


def create(request):
    # todos 작성하기
    # T`odo.objects.create(content=request.POST.get('content'), user_id=request.user.id)

    user = request.user
    todo = Todo(user=user)
    form = TodoForm(request.POST, instance=todo)

    if form.is_valid():
        form.save()

    # movie = Movie.objects.get(pk=id)
    # score = Score(movie=movie)
    # form = ScoreForm(request.POST, instance=score)

    return redirect('todos:home')


def check(request, todo_id):
    # 특정 id를 가진 TODO를 뽑아 Completed = True
    todo = Todo.objects.get(id=todo_id)
    if todo.completed:
        todo.completed = False
    else:
        todo.completed = True
    todo.save()

    return redirect('todos:home')


def delete(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    todo.delete()
    return redirect('todos:home')

lecture/ssafy_190322/todo/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.
# '/users/' => 홈페이지
# '/users/login' => 로그인 화면


def home(request):
    return render(request, 'users/home.html')


def login_user(request):
    # /users/login GET  -> 로그인 창을 render
    # /users/login POST  -> 로그인(유저 검증)
        # 만약에 username, password 넘어온 값이 DB에 저장된 값과 같다면,
        #     로그인
        # 아니면,
        #     실패
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # 1. 사용자가 로그인 되었을 때
            #
            messages.success(request, "로그인 성공")
            return redirect('todos:home')
        else:
            # 2. 로그인이 되지 않았을 때
            messages.warning(request, '로그인 실패, 다시 시도해 주세요.')
            return redirect('users:login')

    else:
        return render(request, 'users/login.html')


def logout_user(request):
    # 유저를 로그아웃 시킨다.
    logout(request)
    # 유저에게 로그아웃이 되었다는 메세지를 전달한다.
    messages.success(request, "로그아웃 되었습니다.")
    return redirect('todos:home')


def register(request):
    if request.method == "POST":
        # 회원가입 시키기(DB에 사용자 정보를 저장)
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('todos:home')
    else:
        # 회원정보를 받는 form 보여주기
        form = UserCreationForm()
        return render(request, 'users/users.html', {'form': form})

lecture/ssafy_190322/todo/shout/templates/shout/form.html
{% extends 'users/base.html' %}

{% if request.resolver_match.url_name == "create" %}
    <h1>이 페이지는 작성페이지입니다.</h1>
{% else %}
    <h1>이 페이지는 수정페이지입니다.</h1>
{% endif %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

lecture/ssafy_190322/todo/shout/templates/shout/home.html
{% extends 'users/base.html' %}

{% block content %}
    <h1>고객센터</h1>
    <a href="{% url 'shout:create' %}">문의하기</a>

    <hr>

    <h2>문의내용</h2>
    {% for shout in shouts %}
        <p>
            id : {{ shout.id }}
            제목 : {{ shout.title }}
            내용 : {{ shout.content }}
            <a href="{% url 'shout:update' shout.id %}">[수정]</a>
        </p>
    {% endfor %}

{% endblock %}

lecture/ssafy_190322/todo/todos/templates/todos/home.html
{% extends 'users/base.html' %}

{% block content %}
    {% if todos %}
        <h1 class="text-center">Todo List</h1>
        <form action="{% url 'todos:create' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" name="content">
            </div>
            <div class="form-group">
                <button class="btn btn-primary">만들기</button>
            </div>
        </form>

        <table class="table">
            <thead>
                <tr>
                <th scope="col">해야 할 일</th>
                <th scope="col">체크</th>
                <th scope="col">삭제</th>
                </tr>
            </thead>
            <tbody>
                {% for todo in todos %}
                    {% if not todo.completed %}
                        <tr>
                            <td>{{ todo.content }}</td>
                            <td><form action="{% url 'todos:check' todo.id %}"><input type="checkbox" class="form-check-input m-auto" onclick="this.form.submit();"></form></td>
                            <td><a href="{% url 'todos:delete' todo.id %}">[삭제]</a></td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>

        <table class="table">
            <thead>
                <tr>
                <th scope="col">완료한 일</th>
                <th scope="col">체크</th>
                <th scope="col">삭제</th>
                </tr>
            </thead>
            <tbody>
                {% for todo in todos %}
                    {% if todo.completed %}
                        <tr>
                            <td><strike>{{ todo.content }}</strike></td>
                            <td><form action="{% url 'todos:check' todo.id %}"><input type="checkbox" class="form-check-input m-auto" onclick="this.form.submit();" checked></form></td>
                            <td><a href="{% url 'todos:delete' todo.id %}">[삭제]</a></td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h1 class="text-center">로그인이 필요합니다.</h1>
    {% endif %}

{% endblock %}