ssafy_project/last_project/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.list, name="list"),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_id>/', views.detail, name='detail'),
    path('<int:user_id>/follow/', views.follow, name="follow"),
    path('<int:user_id>/followers/', views.followers, name="followers"),
    path('<int:user_id>/followings/', views.followings, name="followings"),
]

ssafy_project/last_project/last_project/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views as movie_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('', movie_views.movie_list),
]

ssafy_project/last_project/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_id>/', views.detail, name="detail"),
    path('<int:movie_id>/score/new', views.create_score, name='create_score'),
    path('<int:movie_id>/score/<int:score_id>/delete', views.delete_score, name="delete"),
    path('<int:movie_id>/score/<int:score_id>/update', views.update_score, name="update"),
    path('dbmake/', views.movie_db),
    path('dbmake2/', views.movie_db2),
]

ssafy_project/last_project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR&amp;subset=korean" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon.png' %}">

    {% block title %}
    {% endblock %}
</head>
<body style="font-family: 'Noto Sans KR', sans-serif;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/movie/"><img class="mr-1" src="{% static 'img/mom_logo.png' %}" alt="logo" width="50" height="50"> LIFE THEATER </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:detail' user_id=user.id %}"><img src="{% static 'img/profile2.png' %}" alt="profile" width="20" height="20">  {{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}" ><img src="{% static 'img/profile3.png' %}" alt="profile" width="20" height="20">  LOGIN</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">SIGNUP</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    </nav>


    {% block body %}
    {% endblock %}
    <hr>
    <div class="container">

        {% block container %}

        {% endblock %}
    </div>
</body>

<footer class="footer mt-5 py-3 text-muted bg-light">
  <div class="container">
    <p class="float-right">
      <a href="#">Top</a>
    </p>
    <p>본 콘텐츠의 저작권은 저작권자 또는 제공처에 있으며, 이를 무단 이용하는 경우 저작권법 등에 따라 법적 책임을 질 수 있습니다.</p>
    <p>
        사업자등록번호 : 220-61-42412 <span> 신고번호 </span> : 서울강남 제 2019 - 157호 <span> 대표이사 : 김경태, 이한성</span><br>
        주소 : 서울특별시 강남구 테헤란로 212 702호 <span>광고문의 : 02-3429-5364</span>
    </p>
    <address>
        <a><img src="{% static 'img/favicon.png' %}" width="15" height="auto" alt="MOM"></a><!-- N=a:fot.nhn -->
        <em>Copyright ©</em>
        <a href="http://edu.ssafy.com/" target="_blank">MOM Corp.</a><!-- N=a:fot.corp -->
        <span>All Rights Reserved.</span>
    </address></div>
</footer>

</html>